/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StoatConfigSchemaRendered {
  version: number;
  enabled?: boolean;
  comment_template_file?: string;
  plugins?: {
    static_hosting?: StaticHostingPluginRenderedMap;
    json?: JsonPluginRenderedMap;
    image_diff?: ImageDiffPluginRenderedMap;
    job_runtime?: JobRuntimePluginRendered;
    [k: string]: unknown;
  };
  updated_at?: string;
  views?: {
    plugins?: {
      static_hosting?: {
        github: {
          table: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface StaticHostingPluginRenderedMap {
  [k: string]: StaticHostingPluginRendered;
}
export interface StaticHostingPluginRendered {
  metadata?: {
    [k: string]: unknown;
  };
  path: string;
  file_viewer?: boolean;
  link: string;
  sha: string;
  status: string;
  [k: string]: unknown;
}
export interface JsonPluginRenderedMap {
  [k: string]: JsonPluginRendered;
}
export interface JsonPluginRendered {
  metadata?: {
    [k: string]: unknown;
  };
  path: string;
  value: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface ImageDiffPluginRenderedMap {
  [k: string]: ImageDiffPluginRendered;
}
export interface ImageDiffPluginRendered {
  metadata?: {
    [k: string]: unknown;
  };
  image?: string;
  baseline?: string;
  image_url: string;
  baseline_url: string;
  diff_url: string;
  [k: string]: unknown;
}
export interface JobRuntimePluginRendered {
  width: number;
  height: number;
  runtime: unknown[];
  [k: string]: unknown;
}
