name: Test Kubernetes Plugin
on:
  pull_request:
    branches:
      - main
    paths:
      - 'action/**'
      - '.stoat/**'
      - '.github/workflows/test-kubernetes.yaml'
  push:
    branches:
      - main
    paths:
      - 'action/**'
      - '.stoat/**'
      - '.github/workflows/test-kubernetes.yaml'

defaults:
  run:
    working-directory: action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/action/node_modules
            ${{ github.workspace }}/cli/node_modules
          key: ${{ runner.os }}-node-16-cli-${{ hashFiles('cli/yarn.lock') }}-${{ hashFiles('action/yarn.lock') }}
      - name: Install action dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      - name: Run whalesay
        run: |
          kubectl apply -f ../kubernetes/whalesay.yaml
          sleep 30
      - name: Dump Kubernetes Logs
        run: |
          yarn script scripts/testKube.ts
      - name: Run Stoat Action
        uses: ./
        if: always()
        with:
          kubernetes: default, kube-system
